create table users
(
    user_id     integer not null generated by default as identity (start with 1, increment by 1),
    fullname    varchar(255),
    email       varchar(255),
    password    varchar(255),
    lastlogdate timestamp,
    primary key (user_id)
);

--
--  INITIAL "TEST" DATA
--

-- CREATE users

insert into users (fullname, email, password, lastlogdate)
values ('USER LOGIN1', 'LOGIN1@EXAMPLE.COM', 'password', {TS '2013-01-04 11:14:21.746123'});
insert into users (fullname, email, password, lastlogdate)
values ('USER LOGIN2', 'LOGIN2@EXAMPLE.COM', 'password', {TS '2013-01-04 12:14:21.746123'});
insert into users (fullname, email, password, lastlogdate)
values ('USER LOGIN3', 'LOGIN3@EXAMPLE.COM', 'password', {TS '2013-01-04 13:14:21.746123'});
insert into users (fullname, email, password, lastlogdate)
values ('USER LOGIN4', 'LOGIN4@EXAMPLE.COM', 'password', {TS '2013-01-04 14:14:21.746123'});
insert into users (fullname, email, password, lastlogdate)
values ('USER LOGIN5', 'LOGIN5@EXAMPLE.COM', 'password', {TS '2013-01-04 15:14:21.746123'});
insert into users (fullname, email, password, lastlogdate)
values ('USER LOGIN6', 'LOGIN6@EXAMPLE.COM', 'password', {TS '2013-01-04 16:14:21.746123'});
insert into users (fullname, email, password, lastlogdate)
values ('USER LOGIN7', 'LOGIN7@EXAMPLE.COM', 'password', {TS '2013-01-04 17:14:21.746123'});




